# 基线：Flutter 官方推荐规则集
include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true          # 作用：严格类型转换，避免隐式/不安全的 as
    strict-inference: true      # 作用：严格类型推断，减少动态类型漏网
    strict-raw-types: true      # 作用：禁止原始泛型，统一写出类型参数

  errors:
    missing_required_param: error                      # 作用：缺失必填命名参数直接报错
    missing_return: error                              # 作用：函数签名要求返回值但分支未返回时报错
    dead_code: error                                   # 作用：标记死代码，避免逻辑误判
    invalid_use_of_visible_for_testing_member: error   # 作用：禁止使用仅测试可见的 API
    invalid_use_of_internal_member: error              # 作用：禁止调用内部实现细节
    use_build_context_synchronously: error             # 作用：防止 await 后误用 BuildContext
    invalid_annotation_target: ignore                  # 作用：忽略生成代码上的注解目标告警以降噪

  exclude:
    - "**/*.g.dart"            # 作用：排除 json_serializable 等生成文件
    - "**/*.freezed.dart"      # 作用：排除 freezed 生成文件
    - "**/*.gen.dart"          # 作用：排除约定的生成后缀
    - "lib/**/*.gr.dart"       # 作用：排除 go_router/auto_route 生成文件
    - "lib/**/generated/**"    # 作用：排除 l10n 等生成目录
    - "build/**"               # 作用：排除构建产物
    - ".dart_tool/**"          # 作用：排除工具缓存

linter:
  rules:
    # ---- 一致性与可读性 ----
    always_declare_return_types: true                  # 作用：显式返回类型，便于阅读与重构
    prefer_final_locals: true                          # 作用：局部变量默认不可变，降低副作用
    prefer_final_fields: true                          # 作用：类字段尽量 final，便于推理
    prefer_const_constructors: true                    # 作用：可用 const 的构造函数使用 const
    prefer_const_literals_to_create_immutables: true   # 作用：不变集合使用 const
    prefer_const_declarations: true                    # 作用：局部常量使用 const
    directives_ordering: true                          # 作用：固定 import/export 顺序，diff 更干净
    sort_pub_dependencies: true                        # 作用：pubspec 依赖排序
    always_put_required_named_parameters_first: true   # 作用：必填命名参数优先展示
    lines_longer_than_80_chars: false                  # 作用：放宽 80 列限制，便于移动端文案

    # ---- 空安全 ----
    unnecessary_late: true                             # 作用：移除不必要的 late
    unnecessary_nullable_for_final_variable_declarations: true  # 作用：减少不必要的可空声明
    avoid_returning_null_for_future: true              # 作用：Future 不返回 null，避免判空混乱

    # ---- 异步与资源释放 ----
    cancel_subscriptions: true                         # 作用：订阅需取消，避免泄漏
    close_sinks: true                                  # 作用：Sink/Controller 需关闭
    discarded_futures: true                            # 作用：禁止丢弃未处理的 Future
    avoid_void_async: true                             # 作用：避免 async 返回 void，便于链式处理与错误捕获
    unnecessary_await_in_return: true                  # 作用：返回处移除多余 await

    # ---- Flutter 特有 ----
    use_key_in_widget_constructors: true               # 作用：Widget 支持 Key，利于 diff/重排
    sized_box_for_whitespace: true                     # 作用：用 SizedBox 代替仅用于占位的空 Container
    avoid_unnecessary_containers: true                 # 作用：减少无意义包裹层

    # ---- 日志与错误处理 ----
    avoid_print: false                                  # 作用：禁用 print，使用统一日志
    only_throw_errors: true                            # 作用：仅抛出 Error/Exception，不抛字符串
    use_rethrow_when_possible: true                    # 作用：需要上抛时使用 rethrow 保留栈

    # ---- API/健壮性 ----
    avoid_dynamic_calls: true                          # 作用：禁止对 dynamic 直接调用

    # ---- 下列规则按需开启（存在分歧/可能误报/收益有限）----
    # prefer_single_quotes: true                       # 作用：统一使用单引号
    # prefer_expression_function_bodies: true          # 作用：简单函数用 => 简化
    # sort_constructors_first: true                    # 作用：构造器排在成员前
    # no_leading_underscores_for_local_identifiers: true # 作用：局部标识符不以下划线开头
    # join_return_with_assignment: true                # 作用：返回前合并赋值
    # cascade_invocations: true                        # 作用：同对象多次调用用级联 ..
    # unnecessary_to_list_in_spreads: true             # 作用：移除多余 toList()
    # avoid_returning_null: true                       # 作用：避免返回 null（在 T? 场景可能多余）
    # avoid_field_initializers_in_const_classes: true  # 作用：约束 const 类字段初始化
    # parameter_assignments: true                      # 作用：避免修改入参
    # prefer_const_constructors_in_immutables: true    # 作用：不可变类优先 const 构造
