# Uncomment this line to define a global platform for your project
platform :ios, '16.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        # 启用权限
        'PERMISSION_PHOTOS=1',            # 相册
        'PERMISSION_CAMERA=1',            # 摄像头
        'PERMISSION_MICROPHONE=1',        # 麦克风
        'PERMISSION_SPEECH_RECOGNIZER=1', # 语音识别

        # 禁用权限
        'PERMISSION_CONTACTS=0',          # 联系人
        'PERMISSION_LOCATION=0',          # 定位
        'PERMISSION_CALENDAR=0',          # 日历
        'PERMISSION_EVENTS=0',            # 日历事件
        'PERMISSION_REMINDERS=0',         # 提醒事项
        'PERMISSION_BLUETOOTH=0',         # 蓝牙
        'PERMISSION_MOTION=0',            # 运动与健身
        'PERMISSION_SENSORS=0',           # 身体传感器
        'PERMISSION_MEDIA_LIBRARY=0',     # 媒体库
        'PERMISSION_APP_TRACKING_TRANSPARENCY=0', # 广告追踪
        'PERMISSION_CRITICAL_ALERTS=0',   # 关键警报
        'PERMISSION_NOTIFICATIONS=0',     # 通知
        'PERMISSION_USER_NOTIFICATIONS=0',# 用户通知
        'PERMISSION_ASSISTANT=0',         # Siri/助理
      ]
    end
  end
end